name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icon/
    - assets/images/
    - assets/json/lang/
    - assets/json/menu/
  # assets:
  #   - assets/icon
  #   - assets/images
  #   - assets/json
  #   - assets/lang
  uses-material-design: true
  fonts:
    - family: kanit
      fonts:
        - asset: assets/fonts/kanit/Kanit.ttf
        - asset: assets/fonts/kanit/Kanit-Light.ttf
        - asset: assets/fonts/kanit/Kanit-Bold.ttf
